# Generated by Django 5.0 on 2024-02-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='MailingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_try', models.DateTimeField(verbose_name='Дата и время попытки')),
                ('status', models.CharField(choices=[('Успешно', 'Successfully'), ('Неудачно', 'Failed'), ('Неизвестно', 'Unknown')], default='Неизвестно', verbose_name='Статус попытки')),
                ('response', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ответ почтового сервера')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
            },
        ),
        migrations.CreateModel(
            name='MailingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Тема сообщения')),
                ('body', models.TextField(verbose_name='Текст сообщения')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='MailingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название рассылки')),
                ('start_time', models.DateTimeField(verbose_name='Начальное время рассылки')),
                ('stop_time', models.DateTimeField(verbose_name='Конечное время рассылки')),
                ('periodicity', models.CharField(choices=[('Ежедневно', 'Daily'), ('Еженедельно', 'Weekly'), ('Ежемесячно', 'Monthly')], default='Ежедневно', verbose_name='Периодичность')),
                ('status', models.CharField(choices=[('Выполнена', 'Completed'), ('Создана', 'Created'), ('В работе', 'Launched')], default='Создана', verbose_name='Статус')),
                ('is_active', models.BooleanField(default=True, verbose_name='Состояние активности')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'permissions': [('set_active', 'может менять состояние активности')],
            },
        ),
    ]
