# Generated by Django 5.0 on 2023-12-28 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='MailingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_try', models.DateTimeField(verbose_name='Дата и время попытки')),
                ('status', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ответ сервера')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail_sender.client', verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
            },
        ),
        migrations.CreateModel(
            name='MailingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Тема письма')),
                ('body', models.TextField(verbose_name='Тело письма')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail_sender.client', verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='MailingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Начальное время рассылки')),
                ('stop_time', models.DateTimeField(verbose_name='Конечное время рассылки')),
                ('periodicity', models.CharField(choices=[('DL', 'Daily'), ('WK', 'Weekly'), ('ML', 'Monthly')], default='DL', max_length=2, verbose_name='Периодичность')),
                ('status', models.CharField(choices=[('CMP', 'Completed'), ('CRT', 'Created'), ('LNC', 'Launched')], default='CRT', max_length=3, verbose_name='Статус')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail_sender.client', verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
    ]
